### PR TITLE
collections: moving ovirt-ansible-disaster-recovery to ovirt-ansible-collection

### PR DESCRIPTION
**Pull request by barpavel**
The purpose of this patch is to keep the Disaster Recovery sources equal to the ones moved to the ovirt-ansible-collection repository.
Thus the last version of DR in:
https://github.com/oVirt/ovirt-ansible-disaster-recovery
should be equal to the initial version in:
https://github.com/oVirt/ovirt-ansible-collection/tree/master/roles
where the development will continue.

While moving the DR project to the ovirt-ansible-collection project, certain CI requirements should be met. This patch will include fixes of the CI tests' failures.

Signed-off-by: Pavel Bar <pbar@redhat.com>

### CODE REVIEW

**Comment by mwperina** [comment]
Why do you want to do this? As soon as the role is merged into oVirt Ansible Collection, we should make this repo readonly and mention that development continues only in oVirt Ansible Collection

**Comment by barpavel** [comment]
> Why do you want to do this? As soon as the role is merged into oVirt Ansible Collection, we should make this repo readonly and mention that development continues only in oVirt Ansible Collection

You are right - after transfer of the files to oVirt Ansible Collection this repo will become deprecated/readonly.
These are the reason of what I do:
1) In case of issues I want some version history documentation *what* has changed from the last working DR version and *why*. Otherwise there will be a difference between the last version here and the first version there (pushed as 1 big chunk of files) and it will be hard to understand why file X or file Y of DR differ between the github locations (is it by mistake, is that on purpose, what was the reason for the change, etc.)
2) When this patch will be ready I would be happy if you (and probably Martin Necas) look on the changes that I did when moving to collections to verify I didn't do something incorrect. Definitely it will be hard to do when looking on the big chunk of files added to the collections as the first patch, no one will do a manual diff between the versions. For instance I have some doubts regarding one of the commits in this patch: "CI: fixing CI errors (boilerplate)" - from one side I add 2 lines to be Python 2 compatible, on the other hand the files contain the "#!/usr/bin/python3" line. When changing to "#!/usr/bin/python" (without "3" as Python version as in Python files in the collection project) the CI in this branch fails. So I would like some advises regarding the issue.

**Comment by mwperina** [comment]
OK, no problem. I've just noticed, that you have all the changes split into separate commits, while in https://github.com/oVirt/ovirt-ansible-collection/pull/134 you are forcing pushing the same commit, so it would probably make sense, to have the same commits on both PRs. Or am I missing something?

**Comment by barpavel** [comment]
> OK, no problem. I've just noticed, that you have all the changes split into separate commits, while in [oVirt/ovirt-ansible-collection#134](https://github.com/oVirt/ovirt-ansible-collection/pull/134) you are forcing pushing the same commit, so it would probably make sense, to have the same commits on both PRs. Or am I missing something?

This PR contains a series of commits needed to fix the CI issues at collection repository. I split it to several commits to see what was changed exactly in order to stabilize the CI at the other repository. I want to allow "continuity of code", that is the *last commit* here is a *first commit* of [oVirt/ovirt-ansible-collection#134](https://github.com/oVirt/ovirt-ansible-collection/pull/134). And from there on I continue with additional changes related to moving to collections split to separate commits at the new repository inside [oVirt/ovirt-ansible-collection#134](https://github.com/oVirt/ovirt-ansible-collection/pull/134). I just didn't' want to have a delta in code between ending point here and starting point there.
I hope I explained my intentions clear :)

**Comment by barpavel** [comment]
Verified today on Oct 21st.

**Comment by mwperina** [comment]
> Verified today on Oct 21st.

Great news, thanks Pavel!

**Review by shenitzky — APPROVED** [review]

**Pull request merged**
