### PR TITLE
Add library directory with updated modules

### PR DESCRIPTION
**Pull request by machacekondra**
This PR adds update modues `ovirt_vms`, `ovirt_templates` and `ovirt_storage_domains`, so the user can use this role with Ansible 2.4.x.

### CODE REVIEW

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci build please

**Comment by machacekondra** [comment]
ci build please

**Comment by mwperina** [comment]
Any reason why such roles were not suffixed with Ansible version (for example ovirt_vms_250.py)? Now it would be harder to get rid of those included roles when we will bump our dependency to Ansible 2.5, no?

**Comment by machacekondra** [comment]
Not anything specific, but there isn't time to look, which task call needs update or non-updated module, as we must release it today and still one more module to come. But I agree we should rename it.

**Pull request merged**
