### PR TITLE
automation: build tagged releases without suffixes

### PR DESCRIPTION
**Pull request by sandrobonazzola**
Allow to build tagged releases without suffixes.

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
@ifireball this will make sense if CI supports "ci re-merge please" also from github, is this the case?

**Review by shenitzky — APPROVED** [review]

**Comment by shenitzky** [comment]
Is this fix still relevant? @sandrobonazzola 
If so, @mwperina can you please review?

**Review by mwperina — APPROVED** [review]
+1

**Comment by ifireball** [comment]
@sandrobonazzola I'm afraid we cannot support that - not sure if the question is still relevant though

**Comment by mnecas** [comment]
I think this PR is no longer relevant because the role should be migrated to the collection.
https://github.com/ovirt/ovirt-ansible-collection

**Pull request closed without merging**
